# Generated by Django 6.0.6 on 2026-07-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=50)),
                ('notes', models.TextField()),
                ('score', models.IntegerField()),
                ('submission', models.BooleanField()),
            ],
        ),
    ]
